INSERT INTO TB_PERFIL (ID_PERFIL, NOME, DESCRICAO, ATIVO) VALUES (1, 'ROLE_ADMINISTRADOR_SISTEMA', 'Administrador do sistema', true)
INSERT INTO TB_PERFIL (ID_PERFIL, NOME, DESCRICAO, ATIVO) VALUES (2, 'ROLE_ADMINISTRADOR_GERAL', 'Administrador do geral', true)
INSERT INTO TB_PERFIL (ID_PERFIL, NOME, DESCRICAO, ATIVO) VALUES (3, 'ROLE_ADMINISTRADOR_LOCAL', 'Administrador do local', true)
INSERT INTO TB_PERFIL (ID_PERFIL, NOME, DESCRICAO, ATIVO) VALUES (4, 'ROLE_USUARIO', 'Usuário', true)
INSERT INTO TB_PERFIL (ID_PERFIL, NOME, DESCRICAO, ATIVO) VALUES (5, 'ROLE_ATENDIMENTO', 'Atendimento', true)
INSERT INTO TB_PERFIL (ID_PERFIL, NOME, DESCRICAO, ATIVO) VALUES (6, 'ROLE_RESPONSAVEL', 'Responsável', true)


-- select 1 from dual;